# Generated by Django 2.0 on 2017-12-19 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20171219_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='weight_field',
            new_name='width_field',
        ),
    ]
